baseURL = "/"
languageCode = "en-us"
title = "LuckyWatcher"
theme = "luckywatcher"

pygmentsStyle = "vs"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
subtitle = "Thoughts, stories and ideas"
mainSections = ["posts"]
mode = "auto"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
